### ISSUE TITLE
Cannot find module 'koa-graceful-shutdown'

### ISSUE THREAD

**Issue by rodhoward** [someimportantcompany/koa-graceful-shutdown#7]
I've been using this library for almost a year now love it!

However this latest update "1.2.0" has broken my code I'm getting:

**Cannot find module 'koa-graceful-shutdown'**

when requiring it:
```const gracefulShutdown = require("koa-graceful-shutdown");```

I think it must be packaging issue seems like the .js file under node_modules is missing altogether. 

Regards
Rod

**Comment by jdrydn** [comment]
@rodhoward Apologies - I was cleaning up at the weekend & updated the core files, but didn't update the `package.json` properly 🤦‍♂️  This has been fixed as of `1.2.1` & I will be deprecating `1.2.0` in NPM shortly!

**Comment by rodhoward** [comment]
Np we've all been there. 

Thanks for the fast turnaround.
